---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - servicemonitor.yml
  - service.yml
  - deployment.yml

configMapGenerator:
  - name: hcloud-exporter
    literals: []

secretGenerator:
  - name: hcloud-exporter
    literals: []

images:
  - name: hcloud-exporter
    newName: quay.io/promhippie/hcloud-exporter
    newTag: latest

...
